language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

addons:
  mariadb: '11.0'
  
install:
- source ~/.nvm/nvm.sh 
- nvm ls-remote
- nvm install stable
- nvm use stable
- npm install
script:
- make 

