dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_install:
  - mysql -u root -e 'create database pomf;'
  - mysql -u root pomf < /home/travis/build/pomf/pomf/mysql_schema.sql
  - echo "ewhal4 is gay"

language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  
install:
- source ~/.nvm/nvm.sh 
- nvm ls-remote
- nvm install stable
- nvm use stable
script:
- make 

